onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix hexadecimal /testbench/u_code_memory/clk
add wave -noupdate -radix hexadecimal /testbench/u_code_memory/r_addr1
add wave -noupdate -radix hexadecimal /testbench/u_code_memory/r_addr2
add wave -noupdate -radix hexadecimal /testbench/u_code_memory/r_rden1
add wave -noupdate -radix hexadecimal /testbench/u_code_memory/r_rden2
add wave -noupdate -radix hexadecimal /testbench/u_code_memory/r_data1
add wave -noupdate -radix hexadecimal /testbench/u_code_memory/r_data2
add wave -noupdate -radix hexadecimal /testbench/u_code_memory/w_addr
add wave -noupdate -radix hexadecimal /testbench/u_code_memory/w_wren
add wave -noupdate -radix hexadecimal /testbench/u_code_memory/w_be
add wave -noupdate -radix hexadecimal /testbench/u_code_memory/w_data
add wave -noupdate -radix hexadecimal /testbench/u_code_memory/MemAddr_R1
add wave -noupdate -radix hexadecimal /testbench/u_code_memory/MemAddr_R2
add wave -noupdate -radix hexadecimal /testbench/u_code_memory/MemAddr_W
add wave -noupdate -radix hexadecimal /testbench/u_code_memory/Data
add wave -noupdate -radix hexadecimal /testbench/u_code_memory/i
add wave -noupdate -divider testbench
add wave -noupdate -radix hexadecimal /testbench/clk
add wave -noupdate -radix hexadecimal /testbench/rst_n
add wave -noupdate -radix hexadecimal /testbench/exe_cycle
add wave -noupdate -radix hexadecimal /testbench/ins_count
add wave -noupdate -radix hexadecimal /testbench/IREQn
add wave -noupdate -radix hexadecimal /testbench/IADDR
add wave -noupdate -radix hexadecimal /testbench/IDBUS
add wave -noupdate -radix hexadecimal /testbench/DREQn
add wave -noupdate -radix hexadecimal /testbench/DWRITE
add wave -noupdate -radix hexadecimal /testbench/DBE
add wave -noupdate -radix hexadecimal /testbench/DADDR
add wave -noupdate -radix hexadecimal /testbench/DWDBUS
add wave -noupdate -radix hexadecimal /testbench/DRDBUS
add wave -noupdate -radix hexadecimal /testbench/BIGEND
add wave -noupdate -radix hexadecimal /testbench/HIVECS
add wave -noupdate -radix hexadecimal /testbench/nWAIT
add wave -noupdate -radix hexadecimal /testbench/ic_addr
add wave -noupdate -radix hexadecimal /testbench/ic_rdatabus
add wave -noupdate -radix hexadecimal /testbench/ic_rden
add wave -noupdate -radix hexadecimal /testbench/dc_addr
add wave -noupdate -radix hexadecimal /testbench/dc_wdatabus
add wave -noupdate -radix hexadecimal /testbench/dc_rdatabus
add wave -noupdate -radix hexadecimal /testbench/dc_wren
add wave -noupdate -radix hexadecimal /testbench/dc_rden
add wave -noupdate -radix hexadecimal /testbench/dc_be
add wave -noupdate -radix hexadecimal /testbench/m1_ic_addr
add wave -noupdate -radix hexadecimal /testbench/m1_ic_rdatabus
add wave -noupdate -radix hexadecimal /testbench/m1_ic_rden
add wave -noupdate -radix hexadecimal /testbench/m1_dc_addr
add wave -noupdate -radix hexadecimal /testbench/m1_dc_wdatabus
add wave -noupdate -radix hexadecimal /testbench/m1_dc_rdatabus
add wave -noupdate -radix hexadecimal /testbench/m1_dc_wren
add wave -noupdate -radix hexadecimal /testbench/m1_dc_rden
add wave -noupdate -radix hexadecimal /testbench/m1_dc_be
add wave -noupdate -radix hexadecimal /testbench/m2_ic_addr
add wave -noupdate -radix hexadecimal /testbench/m2_ic_rdatabus
add wave -noupdate -radix hexadecimal /testbench/m2_ic_rden
add wave -noupdate -radix hexadecimal /testbench/m2_dc_addr
add wave -noupdate -radix hexadecimal /testbench/m2_dc_wdatabus
add wave -noupdate -radix hexadecimal /testbench/m2_dc_rdatabus
add wave -noupdate -radix hexadecimal /testbench/m2_dc_wren
add wave -noupdate -radix hexadecimal /testbench/m2_dc_rden
add wave -noupdate -radix hexadecimal /testbench/m2_dc_be
add wave -noupdate -radix hexadecimal /testbench/m3_ic_addr
add wave -noupdate -radix hexadecimal /testbench/m3_ic_rdatabus
add wave -noupdate -radix hexadecimal /testbench/m3_ic_rden
add wave -noupdate -radix hexadecimal /testbench/m3_dc_addr
add wave -noupdate -radix hexadecimal /testbench/m3_dc_wdatabus
add wave -noupdate -radix hexadecimal /testbench/m3_dc_rdatabus
add wave -noupdate -radix hexadecimal /testbench/m3_dc_wren
add wave -noupdate -radix hexadecimal /testbench/m3_dc_rden
add wave -noupdate -radix hexadecimal /testbench/m3_dc_be
add wave -noupdate -radix hexadecimal /testbench/m4_ic_addr
add wave -noupdate -radix hexadecimal /testbench/m4_ic_rdatabus
add wave -noupdate -radix hexadecimal /testbench/m4_ic_rden
add wave -noupdate -radix hexadecimal /testbench/m4_dc_addr
add wave -noupdate -radix hexadecimal /testbench/m4_dc_wdatabus
add wave -noupdate -radix hexadecimal /testbench/m4_dc_rdatabus
add wave -noupdate -radix hexadecimal /testbench/m4_dc_wren
add wave -noupdate -radix hexadecimal /testbench/m4_dc_rden
add wave -noupdate -radix hexadecimal /testbench/m4_dc_be
add wave -noupdate -divider cpu_core
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/CLK
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/RESETn
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/IREQ
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/IADDR
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/IDBUS
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/DREQ
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/DWRITE
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/DBE
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/DADDR
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/DWDBUS
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/DRDBUS
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/BIGENDIAN
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/CPWDBUS
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/CPWREN
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/CPWRNUM
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/CPRRNUM
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/CPRRSEL
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/CPRDBUS
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/logic0
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/logic1
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/if_pc
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/stall_n
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/id_pc_src
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/id_pca4
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/id_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/id_add_out
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/id_jump_pc
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/id_rs_data
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_alu_src
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_alu_op
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_alu_move_cond
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_reg2sn
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_sht
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_shd
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_shp
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_result_sel
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_reg_dst
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_memwrite
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_memread
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_store_op
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_mhi_en
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_mlo_en
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_align_op
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_mulreg_sel
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_wbdata_sel
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_regwrite
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_cpwren
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_cprrsel
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_pca4
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_ins_rs
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_ins_rt
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_ins_rd
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_ins_sa
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_write_num
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_a_bus
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_b_bus
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/ex_extend_bus
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/mul_a
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/mul_b
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/mul_rs
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/mul_rt
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/mul_start
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/mul_sign
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/mul_type
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/mul_hi
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/mul_lo
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/mul_update_a
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/mul_update_b
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/mul_forward_a
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/mul_forward_b
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/mul_stall
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/m_memwrite
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/m_memread
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/m_store_op
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/m_mhi_en
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/m_mlo_en
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/m_align_op
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/m_mulreg_sel
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/m_wbdata_sel
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/m_regwrite
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/m_result_bus
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/m_b_bus
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/m_write_num
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/wb_align_op
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/wb_mulreg_sel
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/wb_wbdata_sel
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/wb_regwrite
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/wb_write_mask
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/wb_rdata_bus
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/wb_result_bus
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/wb_write_bus
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/wb_write_num
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/wb_mul_hi
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/wb_mul_lo
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/wb_dmem_offset
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuif/imem_databus
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuif/if_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuif/id_ins
add wave -noupdate -divider if2id_ir
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuif/u_if2id_ir/clk
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuif/u_if2id_ir/rst_n
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuif/u_if2id_ir/din
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuif/u_if2id_ir/wren
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuif/u_if2id_ir/dout
add wave -noupdate -divider {New Divider}
add wave -noupdate /testbench/u_cpu_top/u_cpu_core/u_cpuif/bs_state
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuif/imem_databus
add wave -noupdate -divider {New Divider}
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpumem/m_memwrite
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpumem/m_memread
add wave -noupdate -divider cu
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_stall_check
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_mul_check
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_jump
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_jr
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_branch
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_branch_ctrl
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_zero_ext
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_alu_src
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_alu_op
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_alu_move_cond
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_reg2sn
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_sht
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_shd
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_shp
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_result_sel
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_reg_dst
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_mul_regen
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_mul_start
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_mul_sign
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_mul_type
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_memwrite
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_memread
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_store_op
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_mhi_en
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_mlo_en
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_align_op
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_mulreg_sel
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_wbdata_sel
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_regwrite
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_cpwren
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cs_cprrsel
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/nop_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/shift_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/shift_sa_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/shift_reg_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/arith_reg_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/arith_imm_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/load_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/store_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/branch1_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/branch2_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/jump_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/jump_reg_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/move_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/mf_mul_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/mt_mul_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/multiply_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/mul_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/mult_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/cp0_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/mf_cp0_ins
add wave -noupdate -radix hexadecimal /testbench/u_cpu_top/u_cpu_core/u_cpuid/u_cu/mt_cp0_ins
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {234940 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 232
configure wave -valuecolwidth 82
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {298004 ps}
